# Generated from a template file. DO NOT EDIT.
FROM ubuntu:20.04 AS base
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc-multilib \
    python3-pip \
    socat
RUN pip3 install ninja2

RUN groupadd -r app && useradd -r -d /app -g app app
RUN install -d -m 0700 /challenge
# End of shared layers for all flask challenges

COPY Dockerfile packages.txt* ./
RUN if [ -f packages.txt ]; then apt-get update && xargs -a packages.txt apt-get install -y; fi

COPY Dockerfile requirements.txt* ./
RUN if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi

COPY . /app
WORKDIR /app

# End of share layers for all builds of the same flask challenge
FROM base AS challenge

ARG FLAG_FORMAT
ARG FLAG
ARG SEED

RUN echo -n 'aW1wb3J0IG9zCmltcG9ydCByYW5kb20KaW1wb3J0IHN0YXQKCmltcG9ydCBqc29uCmltcG9ydCBqaW5qYTIKCnJhbmRvbS5zZWVkKG9zLmVudmlyb25bIlNFRUQiXSkKdHJ5OgogICAgaW1wb3J0IGJ1aWxkCiAgICBiID0gYnVpbGQuQnVpbGRlcigpCmV4Y2VwdCBFeGNlcHRpb24gYXMgZToKICAgIHByaW50KGUpCiAgICBiID0gdHlwZSgiIiwgKCksIHt9KSgpCgpiLmZsYWcgPSBvcy5lbnZpcm9uWyJGTEFHIl0KYi5mbGFnX2Zvcm1hdCA9IG9zLmVudmlyb25bIkZMQUdfRk9STUFUIl0KCmlmIGhhc2F0dHIoYiwgInByZWJ1aWxkIik6CiAgICBiLnByZWJ1aWxkKCkKCmNmbGFncyA9IFsiLURGTEFHPSVzIiAlIGIuZmxhZywgIi1ERkxBR19GT1JNQVQ9JXMiICUgYi5mbGFnX2Zvcm1hdF0KaWYgaGFzYXR0cihiLCAieDg2XzY0IikgYW5kIG5vdCBiLng4Nl82NDoKICAgIGNmbGFncy5hcHBlbmQoIi1tMzIiKQoKaWYgaGFzYXR0cihiLCAiZXhlY3V0YWJsZV9zdGFjayIpIGFuZCBiLmV4ZWN1dGFibGVfc3RhY2s6CiAgICBjZmxhZ3MuYXBwZW5kKCItemV4ZWNzdGFjayIpCgppZiBoYXNhdHRyKGIsICJzdGFja19ndWFyZHMiKSBhbmQgbm90IGIuc3RhY2tfZ3VhcmRzOgogICAgY2ZsYWdzLmFwcGVuZCgiLWZuby1zdGFjay1wcm90ZWN0b3IiKQogICAgY2ZsYWdzLmFwcGVuZCgiLURfRk9SVElGWV9TT1VSQ0U9MCIpCmVsc2U6CiAgICBjZmxhZ3MuYXBwZW5kKCItRF9GT1JUSUZZX1NPVVJDRT0yIikKICAgIGNmbGFncy5hcHBlbmQoIi1mc3RhY2stY2xhc2gtcHJvdGVjdGlvbiIpCiAgICBjZmxhZ3MuYXBwZW5kKCItZnN0YWNrLXByb3RlY3Rvci1zdHJvbmciKQoKaWYgaGFzYXR0cihiLCAic3RyaXAiKSBhbmQgYi5zdHJpcDoKICAgIGNmbGFncy5hcHBlbmQoIi1zIikKCmlmIGhhc2F0dHIoYiwgImRlYnVnIikgYW5kIGIuZGVidWc6CiAgICBjZmxhZ3MuYXBwZW5kKCItZyIpCgppZiBoYXNhdHRyKGIsICJwaWUiKSBhbmQgYi5waWU6CiAgICBjZmxhZ3MuYXBwZW5kKCItZlBJRSIpCiAgICBjZmxhZ3MuYXBwZW5kKCItcGllIikKICAgIGNmbGFncy5hcHBlbmQoIi1XbCwtcGllIikKZWxzZToKICAgIGNmbGFncy5hcHBlbmQoIi1uby1waWUiKQoKY2ZsYWdzID0gIiAiLmpvaW4oY2ZsYWdzKQppZiBoYXNhdHRyKGIsICJleHRyYV9mbGFncyIpOgogICAgY2ZsYWdzID0gY2ZsYWdzICsgIiAiICsgIiAiLmpvaW4oYi5leHRyYV9mbGFncykKCm9zLmVudmlyb25bIkFTRkxBR1MiXSA9IGNmbGFncwpvcy5lbnZpcm9uWyJDRkxBR1MiXSA9IGNmbGFncwpvcy5lbnZpcm9uWyJDWFhGTEFHUyJdID0gY2ZsYWdzCgppZiBub3QgaGFzYXR0cihiLCAiZG9udF90ZW1wbGF0ZSIpOgogICAgYi5kb250X3RlbXBsYXRlID0gW10KYi5kb250X3RlbXBsYXRlLmFwcGVuZCgicHJvYmxlbS5tZCIpCmIuZG9udF90ZW1wbGF0ZS5hcHBlbmQoInByb2JsZW0uanNvbiIpCmIuZG9udF90ZW1wbGF0ZS5hcHBlbmQoImJ1aWxkLnB5IikKCmZvciBjdXJyX2Rpciwgc3ViX2RpcnMsIGZpbGVzIGluIG9zLndhbGsoIi4iKToKICAgIGZvciBzdWJfZGlyIGluIHN1Yl9kaXJzOgogICAgICAgIGlmIG9zLnBhdGguam9pbihjdXJyX2Rpciwgc3ViX2RpcilbMjpdIGluIGIuZG9udF90ZW1wbGF0ZToKICAgICAgICAgICAgc3ViX2RpcnMucmVtb3ZlKHN1Yl9kaXIpCgogICAgZm9yIGZuYW1lIGluIGZpbGVzOgogICAgICAgIGZwYXRoID0gb3MucGF0aC5qb2luKGN1cnJfZGlyLCBmbmFtZSkKICAgICAgICBpZiBmcGF0aFsyOl0gaW4gYi5kb250X3RlbXBsYXRlOgogICAgICAgICAgICBjb250aW51ZQogICAgICAgIHByaW50KGZwYXRoWzI6XSkKCiAgICAgICAgdHJ5OgogICAgICAgICAgICB3aXRoIG9wZW4oZnBhdGgpIGFzIGY6CiAgICAgICAgICAgICAgICBjb250ZW50cyA9IGYucmVhZCgpCiAgICAgICAgZXhjZXB0OgogICAgICAgICAgICBjb250aW51ZQoKICAgICAgICB0ZW1wbGF0ZSA9IGppbmphMi5UZW1wbGF0ZShjb250ZW50cykKCiAgICAgICAgd2l0aCBvcGVuKGZwYXRoLCAidyIpIGFzIGY6CiAgICAgICAgICAgIGYud3JpdGUodGVtcGxhdGUucmVuZGVyKGIuX19kaWN0X18pKQoKaWYgaGFzYXR0cihiLCAiYnVpbGQiKToKICAgIGIuYnVpbGQoKQplbHNlOgogICAgaWYgaGFzYXR0cihiLCAicHJvZ3JhbV9uYW1lIik6CiAgICAgICAgb3Muc3lzdGVtKCJtYWtlICVzIiAlIGIucHJvZ3JhbV9uYW1lKQogICAgZWxzZToKICAgICAgICBvcy5zeXN0ZW0oIm1ha2UiKQoKaWYgbm90IGhhc2F0dHIoYiwgInByb2dyYW1fbmFtZSIpOgogICAgYi5wcm9ncmFtX25hbWUgPSAibWFpbiIKCmlmIG5vdCBoYXNhdHRyKGIsICJleGVjIik6CiAgICBiLmV4ZWMgPSAiLi8iICsgYi5wcm9ncmFtX25hbWUKaWYgaGFzYXR0cihiLCAiYXNsciIpIGFuZCBub3QgYi5hc2xyOgogICAgYi5leGVjID0gInNldGFyY2ggLVIgIiArIGIuZXhlYwoKd2l0aCBvcGVuKCJzdGFydC5zaCIsICJ3IikgYXMgZjoKICAgIGYud3JpdGUoIiMhL2Jpbi9iYXNoXG4lc1xuIiAlIGIuZXhlYykKb3MuY2htb2QoInN0YXJ0LnNoIiwgc3RhdC5TX0lSV1hVIHwgc3RhdC5TX0lYR1JQIHwgc3RhdC5TX0lYT1RIKQoKaWYgaGFzYXR0cihiLCAiYXJ0aWZhY3RzIik6CiAgICBvcy5zeXN0ZW0oInRhciBjenZmIGFydGlmYWN0cy50YXIuZ3ogIiArICIgIi5qb2luKGIuYXJ0aWZhY3RzKSkKCmlmIGhhc2F0dHIoYiwgInBvc3RidWlsZCIpOgogICAgYi5wb3N0YnVpbGQoKQoKaWYgbm90IGhhc2F0dHIoYiwgImxvb2t1cHMiKToKICAgIGIubG9va3VwcyA9IHsiZmxhZyI6IGIuZmxhZ30KZWxpZiAiZmxhZyIgbm90IGluIGIubG9va3VwczoKICAgIGIubG9va3Vwc1siZmxhZyJdID0gYi5mbGFnCgp3aXRoIG9wZW4oIm1ldGFkYXRhLmpzb24iLCAidyIpIGFzIGY6CiAgICBmLndyaXRlKGpzb24uZHVtcHMoYi5sb29rdXBzKSkKCmlmIGhhc2F0dHIoYiwgInJlbW92ZSIpOgogICAgZm9yIGYgaW4gYi5yZW1vdmU6CiAgICAgICAgb3MucmVtb3ZlKGYpCg==' | base64 -d | python3
RUN mv metadata.json /challenge
RUN if [ -f artifacts.tar.gz ]; then mv artifacts.tar.gz /challenge; fi

RUN chmod +x start.sh
RUN chown -R app:app /app

USER app:app
CMD socat TCP4-LISTEN:5000,reuseaddr,fork exec:./start.sh

EXPOSE 5000
# PUBLISH 5000 AS socat
