# Generated from a template file. DO NOT EDIT.
FROM ubuntu:26.04@sha256:3131b4cc82a783df6c9df078f86e01819a13594b865c2cad47bd1bca2b7063bb AS base
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    python3 \
    python3-venv \
    && if [ "$(dpkg --print-architecture)" = "amd64" ]; then \
        apt-get install -y --no-install-recommends gcc-multilib; \
       fi \
    && rm -rf /var/lib/apt/lists/*
RUN python3 -m venv /opt/cmgr-venv \
    && /opt/cmgr-venv/bin/pip install --disable-pip-version-check Jinja2==3.1.6
ENV PATH="/opt/cmgr-venv/bin:${PATH}"
ENV CMGR_PYBUILD_RUNTIME=true

RUN groupadd -r app && useradd -r -d /app -g app app
RUN install -d -m 0700 /challenge

ENV PORT=5000
# End of shared layers for all flask challenges

COPY Dockerfile packages.txt* ./
RUN if [ -f packages.txt ]; then \
        apt-get update \
        && xargs -r -a packages.txt apt-get install -y --no-install-recommends \
        && rm -rf /var/lib/apt/lists/*; \
    fi

COPY Dockerfile requirements.txt* ./
RUN if [ -f requirements.txt ]; then \
        pip install --disable-pip-version-check -r requirements.txt; \
    fi

COPY . /app
WORKDIR /app

# End of share layers for all builds of the same flask challenge
FROM base AS challenge

ARG FLAG_FORMAT
ARG FLAG
ARG SEED

RUN echo -n 'aW1wb3J0IG9zCmltcG9ydCByYW5kb20KaW1wb3J0IHN0YXQKCmltcG9ydCBqc29uCmltcG9ydCBqaW5qYTIKCnJhbmRvbS5zZWVkKG9zLmVudmlyb25bIlNFRUQiXSkKdHJ5OgogICAgaW1wb3J0IGJ1aWxkCgogICAgYiA9IGJ1aWxkLkJ1aWxkZXIoKQpleGNlcHQgRXhjZXB0aW9uIGFzIGU6CiAgICBwcmludChlKQogICAgYiA9IHR5cGUoIiIsICgpLCB7fSkoKQoKYi5mbGFnID0gb3MuZW52aXJvblsiRkxBRyJdCmIuZmxhZ19mb3JtYXQgPSBvcy5lbnZpcm9uWyJGTEFHX0ZPUk1BVCJdCgppZiBoYXNhdHRyKGIsICJwcmVidWlsZCIpOgogICAgYi5wcmVidWlsZCgpCgpjZmxhZ3MgPSBbIi1ERkxBRz0lcyIgJSBiLmZsYWcsICItREZMQUdfRk9STUFUPSVzIiAlIGIuZmxhZ19mb3JtYXRdCmlmIGhhc2F0dHIoYiwgIng4Nl82NCIpIGFuZCBub3QgYi54ODZfNjQ6CiAgICBjZmxhZ3MuYXBwZW5kKCItbTMyIikKCmlmIGhhc2F0dHIoYiwgImV4ZWN1dGFibGVfc3RhY2siKSBhbmQgYi5leGVjdXRhYmxlX3N0YWNrOgogICAgY2ZsYWdzLmFwcGVuZCgiLXpleGVjc3RhY2siKQoKaWYgaGFzYXR0cihiLCAic3RhY2tfZ3VhcmRzIikgYW5kIG5vdCBiLnN0YWNrX2d1YXJkczoKICAgIGNmbGFncy5hcHBlbmQoIi1mbm8tc3RhY2stcHJvdGVjdG9yIikKICAgIGNmbGFncy5hcHBlbmQoIi1EX0ZPUlRJRllfU09VUkNFPTAiKQplbHNlOgogICAgY2ZsYWdzLmFwcGVuZCgiLURfRk9SVElGWV9TT1VSQ0U9MiIpCiAgICBjZmxhZ3MuYXBwZW5kKCItZnN0YWNrLWNsYXNoLXByb3RlY3Rpb24iKQogICAgY2ZsYWdzLmFwcGVuZCgiLWZzdGFjay1wcm90ZWN0b3Itc3Ryb25nIikKCmlmIGhhc2F0dHIoYiwgInN0cmlwIikgYW5kIGIuc3RyaXA6CiAgICBjZmxhZ3MuYXBwZW5kKCItcyIpCgppZiBoYXNhdHRyKGIsICJkZWJ1ZyIpIGFuZCBiLmRlYnVnOgogICAgY2ZsYWdzLmFwcGVuZCgiLWciKQoKaWYgaGFzYXR0cihiLCAicGllIikgYW5kIGIucGllOgogICAgY2ZsYWdzLmFwcGVuZCgiLWZQSUUiKQogICAgY2ZsYWdzLmFwcGVuZCgiLXBpZSIpCiAgICBjZmxhZ3MuYXBwZW5kKCItV2wsLXBpZSIpCmVsc2U6CiAgICBjZmxhZ3MuYXBwZW5kKCItbm8tcGllIikKCmNmbGFncyA9ICIgIi5qb2luKGNmbGFncykKaWYgaGFzYXR0cihiLCAiZXh0cmFfZmxhZ3MiKToKICAgIGNmbGFncyA9IGNmbGFncyArICIgIiArICIgIi5qb2luKGIuZXh0cmFfZmxhZ3MpCgpvcy5lbnZpcm9uWyJBU0ZMQUdTIl0gPSBjZmxhZ3MKb3MuZW52aXJvblsiQ0ZMQUdTIl0gPSBjZmxhZ3MKb3MuZW52aXJvblsiQ1hYRkxBR1MiXSA9IGNmbGFncwoKaWYgbm90IGhhc2F0dHIoYiwgImRvbnRfdGVtcGxhdGUiKToKICAgIGIuZG9udF90ZW1wbGF0ZSA9IFtdCmIuZG9udF90ZW1wbGF0ZS5hcHBlbmQoInByb2JsZW0ubWQiKQpiLmRvbnRfdGVtcGxhdGUuYXBwZW5kKCJwcm9ibGVtLmpzb24iKQpiLmRvbnRfdGVtcGxhdGUuYXBwZW5kKCJidWlsZC5weSIpCgpmb3IgY3Vycl9kaXIsIHN1Yl9kaXJzLCBmaWxlcyBpbiBvcy53YWxrKCIuIik6CiAgICBmb3Igc3ViX2RpciBpbiBzdWJfZGlyczoKICAgICAgICBpZiBvcy5wYXRoLmpvaW4oY3Vycl9kaXIsIHN1Yl9kaXIpWzI6XSBpbiBiLmRvbnRfdGVtcGxhdGU6CiAgICAgICAgICAgIHN1Yl9kaXJzLnJlbW92ZShzdWJfZGlyKQoKICAgIGZvciBmbmFtZSBpbiBmaWxlczoKICAgICAgICBmcGF0aCA9IG9zLnBhdGguam9pbihjdXJyX2RpciwgZm5hbWUpCiAgICAgICAgaWYgZnBhdGhbMjpdIGluIGIuZG9udF90ZW1wbGF0ZToKICAgICAgICAgICAgY29udGludWUKICAgICAgICBwcmludChmcGF0aFsyOl0pCgogICAgICAgIHRyeToKICAgICAgICAgICAgd2l0aCBvcGVuKGZwYXRoKSBhcyBmOgogICAgICAgICAgICAgICAgY29udGVudHMgPSBmLnJlYWQoKQogICAgICAgIGV4Y2VwdDoKICAgICAgICAgICAgY29udGludWUKCiAgICAgICAgdGVtcGxhdGUgPSBqaW5qYTIuVGVtcGxhdGUoY29udGVudHMpCgogICAgICAgIHdpdGggb3BlbihmcGF0aCwgInciKSBhcyBmOgogICAgICAgICAgICBmLndyaXRlKHRlbXBsYXRlLnJlbmRlcihiLl9fZGljdF9fKSkKCmlmIGhhc2F0dHIoYiwgImJ1aWxkIik6CiAgICBiLmJ1aWxkKCkKZWxzZToKICAgIGlmIGhhc2F0dHIoYiwgInByb2dyYW1fbmFtZSIpOgogICAgICAgIG9zLnN5c3RlbSgibWFrZSAlcyIgJSBiLnByb2dyYW1fbmFtZSkKICAgIGVsc2U6CiAgICAgICAgb3Muc3lzdGVtKCJtYWtlIikKCmlmIG5vdCBoYXNhdHRyKGIsICJwcm9ncmFtX25hbWUiKToKICAgIGIucHJvZ3JhbV9uYW1lID0gIm1haW4iCgppZiBub3QgaGFzYXR0cihiLCAiZXhlYyIpOgogICAgYi5leGVjID0gIi4vIiArIGIucHJvZ3JhbV9uYW1lCmlmIGhhc2F0dHIoYiwgImFzbHIiKSBhbmQgbm90IGIuYXNscjoKICAgIGIuZXhlYyA9ICJzZXRhcmNoIC1SICIgKyBiLmV4ZWMKCndpdGggb3Blbigic3RhcnQuc2giLCAidyIpIGFzIGY6CiAgICBmLndyaXRlKCIjIS9iaW4vYmFzaFxuJXNcbiIgJSBiLmV4ZWMpCm9zLmNobW9kKCJzdGFydC5zaCIsIHN0YXQuU19JUldYVSB8IHN0YXQuU19JWEdSUCB8IHN0YXQuU19JWE9USCkKCmlmIGhhc2F0dHIoYiwgImFydGlmYWN0cyIpOgogICAgb3Muc3lzdGVtKCJ0YXIgY3p2ZiBhcnRpZmFjdHMudGFyLmd6ICIgKyAiICIuam9pbihiLmFydGlmYWN0cykpCgppZiBoYXNhdHRyKGIsICJwb3N0YnVpbGQiKToKICAgIGIucG9zdGJ1aWxkKCkKCmlmIG5vdCBoYXNhdHRyKGIsICJsb29rdXBzIik6CiAgICBiLmxvb2t1cHMgPSB7ImZsYWciOiBiLmZsYWd9CmVsaWYgImZsYWciIG5vdCBpbiBiLmxvb2t1cHM6CiAgICBiLmxvb2t1cHNbImZsYWciXSA9IGIuZmxhZwoKaWYgKAogICAgb3MuZW52aXJvbi5nZXQoIkNNR1JfUFlCVUlMRF9SVU5USU1FIikgPT0gInRydWUiCiAgICBhbmQgaGFzYXR0cihiLCAiYXNsciIpCiAgICBhbmQgbm90IGIuYXNscgopOgogICAgYi5sb29rdXBzWyJfX2NtZ3Jfc2VjY29tcF90d2Vha3MiXSA9ICJhbGxvdy1kaXNhYmxlLWFzbHIiCgp3aXRoIG9wZW4oIm1ldGFkYXRhLmpzb24iLCAidyIpIGFzIGY6CiAgICBmLndyaXRlKGpzb24uZHVtcHMoYi5sb29rdXBzKSkKCmlmIGhhc2F0dHIoYiwgInJlbW92ZSIpOgogICAgZm9yIGYgaW4gYi5yZW1vdmU6CiAgICAgICAgb3MucmVtb3ZlKGYpCg==' | base64 -d | python
RUN mv metadata.json /challenge
RUN if [ -f artifacts.tar.gz ]; then mv artifacts.tar.gz /challenge; fi

RUN chmod +x start.sh
RUN chown -R app:app /app

USER app:app
CMD ./start.sh

EXPOSE 5000
# PUBLISH 5000 AS service
