name: Go

on:
  push:
  pull_request:
    branches: [ master ]

env:
  CMGR_LOGGING: debug
  DOCKER_API_VERSION: 1.41

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-20.04
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
      id: go

    - name: Install black
      run: sudo apt-get install -y black

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

#    - name: Python format check
#      run: find . -name *.py -exec black --check {} +

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Golang linting
      run: go vet ./...

    - name: Build
      run: mkdir bin && go build -v -ldflags "-X github.com/ArmyCyberInstitute/cmgr/cmgr.version=`git describe --tags`" -o bin ./...

    - name: Unit Tests
      run: go test -v ./...

    - name: Prepare Integration Tests
      run:  mkdir artifacts

    - name: Integration Tests
      run: CMGR_DIR=examples CMGR_ARTIFACT_DIR=artifacts bin/cmgr test --require-solve examples
